[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "ftests"
script = 'fscripts'

optimizer = true
optimizer_runs = 200
solc = "0.8.17"

# comment this line if occurs prevrandao not set error.
evm_version = "shanghai"
